<a href="https://colab.research.google.com/github/yg36/PyTorch-Learning/blob/main/pytorch_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("hello")

hello


In [ ]:
!nvidia-smi

Tue May 12 10:02:33 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   42C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [ ]:
pip install torch

In [ ]:
import torch
print(torch.__version__)

2.10.0+cu128


Creating a tensor

In [ ]:
# tensor can be number, floating, boolean -> no dimension
scalar = torch.tensor(8.98)
scalar

tensor(8.9800)

It has no dimensions

In [ ]:
scalar.ndim

0

In [ ]:
scalar.shape

torch.Size([])

getting the value

In [ ]:
scalar.item()

8.979999542236328

Vector

In [ ]:
vector = torch.tensor([1,2,3])
vector

tensor([1, 2, 3])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([3])

MATRIX

In [ ]:
MATRIX = torch.tensor([[1,2,3],[4,5,6]])
MATRIX

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX.shape

torch.Size([2, 3])

TENSOR

In [ ]:
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0][2][1]

tensor(8)

In [ ]:
TENSOR = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([2, 3, 3])

Random Tensors

In [ ]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.9423, 0.4541, 0.3024, 0.6642],
        [0.6782, 0.9841, 0.7681, 0.4792],
        [0.0950, 0.4332, 0.9333, 0.3827]])

In [ ]:
# replicating an image
image = torch.rand(size=(224,224,3))
image

tensor([[[0.8788, 0.9182, 0.4428],
         [0.3946, 0.7410, 0.4540],
         [0.7788, 0.9675, 0.8013],
         ...,
         [0.9246, 0.3988, 0.3575],
         [0.8996, 0.6642, 0.1147],
         [0.8865, 0.1902, 0.0874]],

        [[0.8513, 0.0268, 0.4396],
         [0.8969, 0.7088, 0.2716],
         [0.2488, 0.9257, 0.8910],
         ...,
         [0.4288, 0.0982, 0.3982],
         [0.0633, 0.9166, 0.2731],
         [0.6494, 0.6163, 0.4125]],

        [[0.0569, 0.7976, 0.2726],
         [0.6946, 0.5674, 0.4826],
         [0.0973, 0.7104, 0.1845],
         ...,
         [0.5224, 0.4317, 0.3802],
         [0.0492, 0.5593, 0.4109],
         [0.7848, 0.3928, 0.0067]],

        ...,

        [[0.8107, 0.8050, 0.5150],
         [0.9375, 0.0363, 0.2822],
         [0.9975, 0.2439, 0.1917],
         ...,
         [0.5278, 0.1706, 0.5315],
         [0.5539, 0.9536, 0.0047],
         [0.0520, 0.1128, 0.4786]],

        [[0.8912, 0.0432, 0.5307],
         [0.6862, 0.9653, 0.5561],
         [0.

Range of tensors

In [ ]:
x = torch.range(0,10)
x

/tmp/ipykernel_2026/2679214220.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  x = torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
# as it will be deprecated, we will use
x = torch.arange(0,100,20)
# arange(start, end, step)
x

tensor([ 0, 20, 40, 60, 80])

Tensor datatypes

In [ ]:
float_32_tensor = torch.tensor([3,  5, 5], dtype=torch.float32, device="cpu")
float_32_tensor

tensor([3., 5., 5.])

Changing dtype of already created tensor

In [ ]:
float_16_tensor = torch.tensor(float_32_tensor, dtype=torch.float16)
float_16_tensor

/tmp/ipykernel_2026/1795881055.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  float_16_tensor = torch.tensor(float_32_tensor, dtype=torch.float16)


tensor([3., 5., 5.], dtype=torch.float16)

Getting info:
1. dtype: tensor.dtype
2. shape: tensor.shape
3. device: tensor.device

In [ ]:
print("datatype is: ",float_16_tensor.dtype)
print("shape is: ", float_16_tensor.shape)
print("device is: ", float_16_tensor.device)

datatype is:  torch.float16
shape is:  torch.Size([3])
device is:  cpu


In [ ]:
print("datatype is: ",float_32_tensor.dtype)
print("shape is: ", float_32_tensor.shape)
print("device is: ", float_32_tensor.device)

datatype is:  torch.float32
shape is:  torch.Size([3])
device is:  cpu


manipulating tensors

In [ ]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
torch.add(tensor, 10)

tensor([11, 12, 13])

In [ ]:
tensor-10

tensor([-9, -8, -7])

In [ ]:
torch.subtract(tensor, 10)

tensor([-9, -8, -7])

In [ ]:
tensor /2

tensor([0.5000, 1.0000, 1.5000])

In [ ]:
torch.divide(tensor, 2)

tensor([0.5000, 1.0000, 1.5000])

In [ ]:
# scalar multiplication
tensor*10

tensor([10, 20, 30])

In [ ]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [ ]:
# Matrix multiplication


In [ ]:
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
tensor @ tensor

tensor(14)

In [ ]:
# tensor.mT
# will give error as it is a 1D array.

In [ ]:
tensor = torch.tensor(([[1,2,3], [4,5,6]]))
tensor
tensor.ndim

2

In [ ]:
tensor.T

tensor([[1, 4],
        [2, 5],
        [3, 6]])

In [ ]:
tensor.mT

tensor([[1, 4],
        [2, 5],
        [3, 6]])

tensor aggregation methods

In [ ]:
tensor = torch.tensor([23,78, 65, 22, 9, 78, 45, 55])
tensor

tensor([23, 78, 65, 22,  9, 78, 45, 55])

In [ ]:
torch.min(tensor)

tensor(9)

In [ ]:
torch.max(tensor)

tensor(78)

In [ ]:
# torch.mean(tensor)
# will give error as mean cant process long(int64) so lets change its dtype
changed_tensor = tensor.type(torch.float32)
torch.mean(changed_tensor)

tensor(46.8750)

In [ ]:
torch.sum(tensor)

tensor(375)

In [ ]:
torch.sum(changed_tensor)

tensor(375.)

Finding positional min and max

In [ ]:
tensor.argmin()

tensor(4)

In [ ]:
tensor.argmax()

tensor(1)

Views

In [ ]:
tensor = torch.arange(1,10)
tensor
tensor.shape

torch.Size([9])

In [ ]:
z = tensor.view(3,3)
z

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
z[2][0] = 99876

In [ ]:
tensor
# tensor also changes bcz they share same memory

tensor([    1,     2,     3,     4,     5,     6, 99876,     8,     9])

Reshaping

In [ ]:
tensor = torch.tensor(torch.randn(4,3))
tensor

/tmp/ipykernel_2026/387490784.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  tensor = torch.tensor(torch.randn(4,3))


tensor([[-1.5052, -1.2102,  0.4400],
        [ 1.0446, -0.7274,  0.7400],
        [ 1.1704, -1.1200,  0.2793],
        [-0.5540, -0.0851,  0.3694]])

In [ ]:
tensor_reshaped = tensor.reshape(12,1)
tensor_reshaped


tensor([[-1.5052],
        [-1.2102],
        [ 0.4400],
        [ 1.0446],
        [-0.7274],
        [ 0.7400],
        [ 1.1704],
        [-1.1200],
        [ 0.2793],
        [-0.5540],
        [-0.0851],
        [ 0.3694]])

In [ ]:
tensor_resized = tensor_reshaped.type(torch.int16)
tensor_resized

tensor([[-1],
        [-1],
        [ 0],
        [ 1],
        [ 0],
        [ 0],
        [ 1],
        [-1],
        [ 0],
        [ 0],
        [ 0],
        [ 0]], dtype=torch.int16)

STacking of tensors

In [ ]:
tensor

tensor([[-1.5052, -1.2102,  0.4400],
        [ 1.0446, -0.7274,  0.7400],
        [ 1.1704, -1.1200,  0.2793],
        [-0.5540, -0.0851,  0.3694]])

In [ ]:
tensor_stacked = torch.stack([tensor, tensor, tensor], dim = 2)
tensor_stacked

tensor([[[-1.5052, -1.5052, -1.5052],
         [-1.2102, -1.2102, -1.2102],
         [ 0.4400,  0.4400,  0.4400]],

        [[ 1.0446,  1.0446,  1.0446],
         [-0.7274, -0.7274, -0.7274],
         [ 0.7400,  0.7400,  0.7400]],

        [[ 1.1704,  1.1704,  1.1704],
         [-1.1200, -1.1200, -1.1200],
         [ 0.2793,  0.2793,  0.2793]],

        [[-0.5540, -0.5540, -0.5540],
         [-0.0851, -0.0851, -0.0851],
         [ 0.3694,  0.3694,  0.3694]]])

unsqueezing

In [ ]:
x

tensor([ 0, 20, 40, 60, 80])

In [ ]:
x_unsqueezed = x.unsqueeze(dim=0)

In [ ]:
x.shape

torch.Size([5])

In [ ]:
x_unsqueezed.shape

torch.Size([1, 5])

squeeze

In [ ]:
x_squeezed = x_unsqueezed.squeeze()
x_squeezed

tensor([ 0, 20, 40, 60, 80])

In [ ]:
x_squeezed.shape

torch.Size([5])

Permute

In [ ]:
x = torch.randn(2,3,5)
x.size()

torch.Size([2, 3, 5])

In [ ]:
x_permuted = torch.permute(x, (2,0,1))

In [ ]:
x_permuted.shape

torch.Size([5, 2, 3])

Accessing elements

In [ ]:
tensor = torch.randn(size=(4,3,2))
tensor

tensor([[[ 0.0564, -1.1426],
         [ 0.3613,  0.7235],
         [ 0.3633, -1.5161]],

        [[ 0.7400,  1.3883],
         [ 1.1507,  0.5346],
         [ 0.3541,  0.4193]],

        [[-0.8586,  1.5041],
         [ 0.5047, -0.8278],
         [-1.4351, -1.0690]],

        [[ 0.7160,  1.4899],
         [-0.0068,  0.6050],
         [-1.2628,  1.7330]]])

In [ ]:
tensor[1]

tensor([[0.7400, 1.3883],
        [1.1507, 0.5346],
        [0.3541, 0.4193]])

In [ ]:
tensor[1][1]

tensor([1.1507, 0.5346])

In [ ]:
tensor[1][1][0]

tensor(1.1507)

slicing

In [ ]:
tensor[:]

tensor([[[ 0.0564, -1.1426],
         [ 0.3613,  0.7235],
         [ 0.3633, -1.5161]],

        [[ 0.7400,  1.3883],
         [ 1.1507,  0.5346],
         [ 0.3541,  0.4193]],

        [[-0.8586,  1.5041],
         [ 0.5047, -0.8278],
         [-1.4351, -1.0690]],

        [[ 0.7160,  1.4899],
         [-0.0068,  0.6050],
         [-1.2628,  1.7330]]])

In [ ]:
tensor[:,1]

tensor([[ 0.3613,  0.7235],
        [ 1.1507,  0.5346],
        [ 0.5047, -0.8278],
        [-0.0068,  0.6050]])

In [ ]:
tensor[:,1,0]

tensor([ 0.3613,  1.1507,  0.5047, -0.0068])

In [ ]:
tensor[1, 1]

tensor([1.1507, 0.5346])

 making tensors from numpy

In [ ]:
import numpy as np

In [ ]:
array = np.arange(1.0,8.0)
array, array.dtype

(array([1., 2., 3., 4., 5., 6., 7.]), dtype('float64'))

In [ ]:
tensor = torch.from_numpy(array)
tensor, tensor.dtype

(tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64), torch.float64)

Making array from tensors

In [ ]:
tensor = torch.ones(2,3,2)
tensor, tensor.dtype

(tensor([[[1., 1.],
          [1., 1.],
          [1., 1.]],
 
         [[1., 1.],
          [1., 1.],
          [1., 1.]]]),
 torch.float32)

In [ ]:
array = tensor.numpy()
array, array.dtype

(array([[[1., 1.],
         [1., 1.],
         [1., 1.]],
 
        [[1., 1.],
         [1., 1.],
         [1., 1.]]], dtype=float32),
 dtype('float32'))

Reproducibility

In [ ]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)
print(random_tensor_C)
torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)
print(random_tensor_D)

print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


Check for GPU

In [ ]:
torch.cuda.is_available()

True

In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [ ]:
torch.cuda.device_count()

1

apple gpu availability

In [ ]:
torch.backends.mps.is_available()

False

Putting tensors or models on gpu

In [ ]:
tensor = torch.tensor([2,2,3])
tensor.device

device(type='cpu')

In [ ]:
# that means default is cpu. Lets change it to gpu
tensor_on_gpu = tensor.to("cuda")
tensor_on_gpu.device
# works only if cuda is available

device(type='cuda', index=0)